<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:xacro="http://ros.org/wiki/xacro"
  name="kurtana">

  <property name="M_PI" value="3.1415926535897931" />

  <!-- ******************** -->
  <!-- *** KURTana Rack *** -->
  <!-- ******************** -->
  
  <include filename="$(find kurt_description)/parts/kurtana_rack.urdf.xacro" />

  <property name="kinect_x_offset" value="0.03" />
  <property name="kinect_y_offset" value="0.0" />
  <property name="kinect_z_offset" value="0.018" />


  <!-- ************************ -->
  <!-- *** Microsoft Kinect *** -->
  <!-- ************************ -->
  
  <include filename="$(find kurt_description)/parts/kinect.urdf.xacro" />
  <xacro:kinect camera="kinect" />

  <joint name="kurtana_kinect_joint" type="fixed">
    <parent link="kurtana_kinect_mounting_plate_link" />
    <child  link="kinect_link" />
    <origin xyz="${kinect_x_offset} ${kinect_y_offset} ${kinect_z_offset}" rpy="0 0 0"/>
  </joint>


  <!-- ************************* -->
  <!-- *** SICK TiM3xx laser *** -->
  <!-- ************************* -->
  
  <include filename="$(find sick_tim3xx)/urdf/sick_tim3xx.urdf.xacro" />
  <xacro:sick_tim3xx laser_link="laser" />

  <joint name="kurtana_laser_joint" type="fixed">
    <parent link="kurtana_baseplate_link" />
    <child link="laser_mount_link" />
    <origin xyz="${baseplate_length/2 - sick_tim3xx_length/2} 0 ${baseplate_height/2}" rpy="0 0 0" />
  </joint>
  

  <!-- **************************** -->
  <!-- *** Neuronics Katana Arm *** -->
  <!-- **************************** -->
  
 <include filename="$(find katana_description)/urdf/katana_300_6m180.urdf.xacro" />
  
 <!-- send katana urdf to param server 
  <param name="robot_description" command="$(find xacro)/xacro.py '$(find katana_description)/urdf/katana_300_6m180.urdf.xacro'" /> -->

  <joint name="kurtana_baseplate_katana_baseplate_joint" type="fixed">
    <parent link="katana_baseplate_link" />
    <child link="katana_base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>


</robot>
